export const continents = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
] as const

export type Continent = (typeof continents)[number]

/**
 * The complete checked-in study-entity continent policy. It uses UN M49 as its
 * baseline, the five product overrides, and supplemental classifications for
 * Taiwan and Kosovo because neither is represented as an M49 country area.
 */
export const continentByEntityCode: Readonly<Record<string, Continent>> = Object.freeze({
  AFG: "Asia",
  AGO: "Africa",
  ALB: "Europe",
  AND: "Europe",
  ARE: "Asia",
  ARG: "South America",
  ARM: "Asia",
  ATG: "North America",
  AUS: "Oceania",
  AUT: "Europe",
  AZE: "Asia",
  BDI: "Africa",
  BEL: "Europe",
  BEN: "Africa",
  BFA: "Africa",
  BGD: "Asia",
  BGR: "Europe",
  BHR: "Asia",
  BHS: "North America",
  BIH: "Europe",
  BLR: "Europe",
  BLZ: "North America",
  BOL: "South America",
  BRA: "South America",
  BRB: "North America",
  BRN: "Asia",
  BTN: "Asia",
  BWA: "Africa",
  CAF: "Africa",
  CAN: "North America",
  CHE: "Europe",
  CHL: "South America",
  CHN: "Asia",
  CIV: "Africa",
  CMR: "Africa",
  COD: "Africa",
  COG: "Africa",
  COL: "South America",
  COM: "Africa",
  CPV: "Africa",
  CRI: "North America",
  CUB: "North America",
  CYP: "Asia",
  CZE: "Europe",
  DEU: "Europe",
  DJI: "Africa",
  DMA: "North America",
  DNK: "Europe",
  DOM: "North America",
  DZA: "Africa",
  ECU: "South America",
  EGY: "Africa",
  ERI: "Africa",
  ESP: "Europe",
  EST: "Europe",
  ETH: "Africa",
  FIN: "Europe",
  FJI: "Oceania",
  FRA: "Europe",
  FSM: "Oceania",
  GAB: "Africa",
  GBR: "Europe",
  GEO: "Asia",
  GHA: "Africa",
  GIN: "Africa",
  GMB: "Africa",
  GNB: "Africa",
  GNQ: "Africa",
  GRC: "Europe",
  GRD: "North America",
  GTM: "North America",
  GUY: "South America",
  HND: "North America",
  HRV: "Europe",
  HTI: "North America",
  HUN: "Europe",
  IDN: "Asia",
  IND: "Asia",
  IRL: "Europe",
  IRN: "Asia",
  IRQ: "Asia",
  ISL: "Europe",
  ISR: "Asia",
  ITA: "Europe",
  JAM: "North America",
  JOR: "Asia",
  JPN: "Asia",
  KAZ: "Asia",
  KEN: "Africa",
  KGZ: "Asia",
  KHM: "Asia",
  KIR: "Oceania",
  KNA: "North America",
  KOR: "Asia",
  KWT: "Asia",
  LAO: "Asia",
  LBN: "Asia",
  LBR: "Africa",
  LBY: "Africa",
  LCA: "North America",
  LIE: "Europe",
  LKA: "Asia",
  LSO: "Africa",
  LTU: "Europe",
  LUX: "Europe",
  LVA: "Europe",
  MAR: "Africa",
  MCO: "Europe",
  MDA: "Europe",
  MDG: "Africa",
  MDV: "Asia",
  MEX: "North America",
  MHL: "Oceania",
  MKD: "Europe",
  MLI: "Africa",
  MLT: "Europe",
  MMR: "Asia",
  MNE: "Europe",
  MNG: "Asia",
  MOZ: "Africa",
  MRT: "Africa",
  MUS: "Africa",
  MWI: "Africa",
  MYS: "Asia",
  NAM: "Africa",
  NER: "Africa",
  NGA: "Africa",
  NIC: "North America",
  NLD: "Europe",
  NOR: "Europe",
  NPL: "Asia",
  NRU: "Oceania",
  NZL: "Oceania",
  OMN: "Asia",
  PAK: "Asia",
  PAN: "North America",
  PER: "South America",
  PHL: "Asia",
  PLW: "Oceania",
  PNG: "Oceania",
  POL: "Europe",
  PRK: "Asia",
  PRT: "Europe",
  PRY: "South America",
  PSE: "Asia",
  QAT: "Asia",
  ROU: "Europe",
  RUS: "Europe",
  RWA: "Africa",
  SAU: "Asia",
  SDN: "Africa",
  SEN: "Africa",
  SGP: "Asia",
  SLB: "Oceania",
  SLE: "Africa",
  SLV: "North America",
  SMR: "Europe",
  SOM: "Africa",
  SRB: "Europe",
  SSD: "Africa",
  STP: "Africa",
  SUR: "South America",
  SVK: "Europe",
  SVN: "Europe",
  SWE: "Europe",
  SWZ: "Africa",
  SYC: "Africa",
  SYR: "Asia",
  TCD: "Africa",
  TGO: "Africa",
  THA: "Asia",
  TJK: "Asia",
  TKM: "Asia",
  TLS: "Asia",
  TON: "Oceania",
  TTO: "North America",
  TUN: "Africa",
  TUR: "Europe",
  TUV: "Oceania",
  TWN: "Asia",
  TZA: "Africa",
  UGA: "Africa",
  UKR: "Europe",
  URY: "South America",
  USA: "North America",
  UZB: "Asia",
  VAT: "Europe",
  VCT: "North America",
  VEN: "South America",
  VNM: "Asia",
  VUT: "Oceania",
  WSM: "Oceania",
  XKX: "Europe",
  YEM: "Asia",
  ZAF: "Africa",
  ZMB: "Africa",
  ZWE: "Africa",
})

export const expectedContinentEntityCount = 197
