import { useEffect, useMemo, useState } from 'react'
import { GeoJSON, MapContainer, Pane, useMap } from 'react-leaflet'
import { borderEntity, borderShape, type BorderPosition, type BorderQuestion } from './borderCountries'
import { selectedBorderFocus } from './borderContextViewport'
import { borderContextGeometry } from './borderContextGeometry'
function Refit({ path, epoch, reducedMotion }: { path: readonly BorderPosition[]; epoch: number; reducedMotion: boolean }) { const map=useMap(); const focus=useMemo(()=>selectedBorderFocus(path),[path]); useEffect(()=>{map.stop();map.fitBounds([[focus.bounds[0],focus.bounds[1]],[focus.bounds[2],focus.bounds[3]]],{animate:!reducedMotion,maxZoom:focus.maxZoom,padding:[focus.padding[0],focus.padding[1]]})},[map,focus,epoch,reducedMotion]);return null }
function Semantics({ label }: { label: string }){const map=useMap();useEffect(()=>{const node=map.getContainer();node.setAttribute('role','application');node.setAttribute('aria-label',label);const invalidate=()=>map.invalidateSize({animate:false,pan:false});const Observer=window.ResizeObserver;const observer=Observer?new Observer(invalidate):undefined;observer?.observe(node);if(!observer)window.addEventListener('resize',invalidate);return()=>{node.removeAttribute('role');node.removeAttribute('aria-label');observer?.disconnect();if(!observer)window.removeEventListener('resize',invalidate)}},[map,label]);return null}
export function EasyBorderContextMap({ question, answerStatus, recenterEpoch }: { question: BorderQuestion; answerStatus?: 'correct'|'revealed'; recenterEpoch: number }) {
  const known=borderShape(question.knownCode!,question.source)!; const knownGeometry=useMemo(()=>borderContextGeometry(known),[known]); const answerGeometry=useMemo(()=>answerStatus?borderContextGeometry(borderShape(question.answerCode!,question.source)!):undefined,[answerStatus,question.answerCode,question.source]); const focus=selectedBorderFocus(question.path)
  const [manualEpoch,setManualEpoch]=useState(0); const reducedMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false; const bounds = [[focus.bounds[0], focus.bounds[1]], [focus.bounds[2], focus.bounds[3]]] as [[number, number], [number, number]]; const padding=[focus.padding[0],focus.padding[1]] as [number,number]
  return <section className="easy-border-context-shell" aria-label={`Border context map for ${borderEntity(question.knownCode!)?.name}`}>
    <MapContainer className="easy-border-context-map" bounds={bounds} boundsOptions={{animate:!reducedMotion,maxZoom:focus.maxZoom,padding}} minZoom={2} maxZoom={18} keyboard scrollWheelZoom worldCopyJump={false} attributionControl={false}>
      <Refit path={question.path} epoch={recenterEpoch+manualEpoch} reducedMotion={reducedMotion}/><Semantics label={`Border context map for ${borderEntity(question.knownCode!)?.name}`}/>
      <Pane name="easy-border-known" style={{zIndex:300}}><GeoJSON data={knownGeometry} interactive={false} style={{color:'#6684af',weight:2,fillColor:'#dbe8ff',fillOpacity:.82}}/></Pane>
      <Pane name="easy-border-answer" style={{zIndex:310}}>{answerGeometry&&<GeoJSON data={answerGeometry} interactive={false} style={{color:answerStatus==='correct'?'#75d4ad':'#e08989',weight:2,fillColor:answerStatus==='correct'?'#3f9678':'#86575b',fillOpacity:.5,dashArray:answerStatus==='revealed'?'6 5':undefined,className:`easy-border-answer easy-border-answer-${answerStatus}`}}/>}</Pane>
      <Pane name="easy-border-line" style={{zIndex:400}}><GeoJSON data={{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:question.path}} as never} interactive={false} style={{color:'#101b2d',weight:8,className:'easy-border-selected-run-halo'}}/><GeoJSON data={{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:question.path}} as never} interactive={false} style={{color:'#ffcf70',weight:4,className:'easy-border-selected-run'}}/></Pane>
    </MapContainer><p className="easy-border-context-hint">Drag to move · scroll or pinch to zoom</p><button type="button" className="text-button easy-border-recenter" onClick={()=>setManualEpoch(value=>value+1)}>Recenter shared border</button>
  </section>
}
